### ISSUE TITLE
Replicating results using huggingface splinter tokenizer and model

### ISSUE THREAD

**Issue by sammys377** [oriram/splinter#12]
Hi I enjoyed reading your paper very much and am trying to replicate the results with splinter-large.  I have not been able to replicate the fine-tuning results with the huggingface models. Is this because the Splinter tokenizer adds a [SEP] token after the [QUESTION] token, whereas during pretraining the [QUESTION] token is in the same sequence as the answer?

**Comment by sammys377** [comment]
Looking into it a bit more, it appears that when the splinter tokenizer is used with squad_convert_examples_to_features, the gold answer spans are shifted to the right two tokens because of the added [QUESTION] token. After tweaking squad_convert_examples_to_features though I am still not able to replicate the few shot results.

**Comment by oriram** [comment]
Hi @sammys377, thanks for showing your interest in our work!
We didn't report results of `splinter-large` in our paper - can you reproduce results with `splinter-base`?
Specifically, following the instructions in our README with `splinter-base` should reproduce our reported results.
Thanks!

**Comment by sammys377** [comment]
Yes, I could but wanted to use splinter-large from huggingface. I think I found the issue: the splinter tokenizer adds a period and a [SEP] token after the question token and squad_convert_examples_to_features in huggingface doesn't account for this. I was able to fix it by incrementing the document start by 2 for the splinter tokenizer.

**Comment by oriram** [comment]
Cool, many thanks!
Any idea how to make this the default behavior?

**Comment by sammys377** [comment]
Here is a quick and dirty fix that I used on my machine:
https://github.com/huggingface/transformers/pull/21069/commits/634a474e2986dc6cbd97fe516b1c1bceedfd704f

**Comment by oriram** [comment]
I see, many thanks!
