### ISSUE TITLE
pretraining data

### ISSUE THREAD

**Issue by MabelLIng** [oriram/splinter#7]
Could please provide the data for pretraining?

**Comment by oriram** [comment]
Hi @MabelLIng ,
Can you please elaborate? 
Thanks!

**Comment by MabelLIng** [comment]
> Hi @MabelLIng ,
> Can you please elaborate?
> Thanks!

the size of Wikipedia datasets is very large and I can't decide which one to choose. If  you can provide the Wikipedia for pretraining ?
Thanks!

**Comment by oriram** [comment]
We used all of Wikipedia for pretraining (about 100 epochs over it). 
Training only on a portion of it will probably result in worse performance.

**Comment by MabelLIng** [comment]
> We used all of Wikipedia for pretraining (about 100 epochs over it).
> Training only on a portion of it will probably result in worse performance.
Do you mean all the data of this url(https://meta.wikimedia.org/wiki/Data_dump_torrents#English_Wikipedia)?

**Comment by oriram** [comment]
Yes, see this dump https://dumps.wikimedia.org/enwiki/20210920/ for example.
We download it and then process it using [wikiextractor](https://github.com/attardi/wikiextractor/).

**Comment by MabelLIng** [comment]
> Yes, see this dump https://dumps.wikimedia.org/enwiki/20210920/ for example.
> We download it and then process it using [wikiextractor](https://github.com/attardi/wikiextractor/).

Thanks a lot!
